### PR TITLE
add Expand listener and possiblity to toggle on click automatically

### PR DESCRIPTION
**Pull request by OHoussein**
Expand listener (fire event when the expand status is changed)
toggle on click automatically by adding `    app:el_toggle_on_click="true"` on `ExpandableLinearLayout` to toggle automatically when the layout is clicked

### CODE REVIEW

**Comment by cachapa** [comment]
Can you clarify the benefit of adding this?

In my understanding this replaces the onClickListener (an Android standard that all developers are familiar with) with a custom handler that essentially does the same thing but is less flexible.

More code means more maintenance effort and more possibility for bugs to hide. I want to be sure that any code added to the library is justified by its usefulness.

**Comment by OHoussein** [comment]
By adding this, you can create an expandable content without calling findViewById, setOnClickListener,  onClick, toggle (but it's optionnal).

**Comment by cachapa** [comment]
I'm not a big fan of hardcoded behaviour, particularly when it only covers one of the many possible use cases.
This could be handled in a much cleaner way by the client by simply extending the layout and adding the onClick behaviour there. It would accomplish the same goal without adding complexity to the upstream code.

Regarding the new ExpandListener, can you give me a practical example where you'd need it and the existing OnExpansionUpdateListener wouldn't do?

**Comment by OHoussein** [comment]
I think that OnExpansionUpdateListener is for handling animation changes, ExpandListener is for handling expand/collapse events.
I'm a fan of simple, comprehensible and customisable code.

**Comment by cachapa** [comment]
I was asking for a specific real-world example where you would need the ExpandListener and the existing OnExpansionUpdateListener wouldn't do.

**Comment by OHoussein** [comment]
Can you can detect expand/collapse events with OnExpansionUpdateListener ?

**Comment by cachapa** [comment]
Sure. If the value is 0 the view is collapsed, otherwise it's expanded.
You can also call isExpanded() at any time (for example, in response to an OnExpansionUpdateListener callback.

**Comment by OHoussein** [comment]
But it think it's more comprehensible with `onToggle(boolean expanded) `

**Comment by cachapa** [comment]
I disagree. You failed to provide a specific example where you would use that callback in an actual product. The fact that it's more understandable is irrelevant if no one will use the feature.
I don't want to add code unless there's a clear benefit to the user of the library, especially when there's a perfectly acceptable alternative already implemented.

Sorry, but I'm rejecting this pull request.

**Pull request closed without merging**
