### PR TITLE
fixed state not updated when animation is set false.

### PR DESCRIPTION
**Pull request by KiBa1215**
Fixed a problem that when expand or collpse without animation, the state will not update.

### CODE REVIEW

**Comment by cachapa** [comment]
Sorry for the delay in accepting this, but I've been terribly busy.
Thanks for your patch!

**Comment by cachapa** [comment]
Merged this too soon. By setting the state in setExpansionInternal(), you disabled the EXPANDING and COLLAPSING states.

I'm reverting this and will try to find a better solution.

**Comment by KiBa1215** [comment]
Yes, you are right. I was thoughtless. 
I think the method can be modified like following? Because there is no EXPANDING or COLLAPSING state when the animation is false:
`    private void setExpansionInternal(float expansion, boolean animate) {
        if(!animate){
            // update the state
            state = expansion == 0 ? COLLAPSED : EXPANDED;
        }

        setVisibility(state == COLLAPSED ? GONE : VISIBLE);

        this.expansion = expansion;
        requestLayout();

        if (listener != null) {
            listener.onExpansionUpdate(expansion, state);
        }
    }`

**Comment by KiBa1215** [comment]
Yes, you are right. I was thoughtless. 
I think the method can be modified like following? Because there is no EXPANDING or COLLAPSING state when the animation is false:
```
private void setExpansionInternal(float expansion, boolean animate) {
        if(!animate){
            // update the state
            state = expansion == 0 ? COLLAPSED : EXPANDED;
        }
        setVisibility(state == COLLAPSED ? GONE : VISIBLE);
        this.expansion = expansion;
        requestLayout();

        if (listener != null) {
            listener.onExpansionUpdate(expansion, state);
        }
 }
```

**Comment by cachapa** [comment]
I've already fixed the problem in 621ffdd0
I took the oportunity to simplify the code and remove the `setExpansionInternal` I never liked anyway. Thanks again for the report and for the initial PR.

**Pull request merged**
